### ISSUE TITLE
dragging canvas clears selection

### ISSUE THREAD

**Issue by rogpeppe** [nomeata/incredible#110]
When selecting several blocks to make a custom block, if you drag the canvas (for example to make another block visible), the selection is lost and all the blocks must be selected again.

I'd expect the blue-highlighted (selected) blocks to remain selected even when the canvas is dragged.

**Comment by nomeata** [comment]
Oh, that’s indeed annoying, thanks for the report.

**Comment by yuxuanchiadm** [comment]
Fixed in #117

**Comment by nomeata** [comment]
I believe thr fix has been merged
