### ISSUE TITLE
Please explain these complicated blocks

### ISSUE THREAD

**Issue by void4** [nomeata/incredible#115]
I've searched far and wide, but I couldn't find a single introduction to what these blocks represent and how they behave.

It seems that this implication block gives you the left side as an assumption which you can then use to prove (possibly in combination with other assumptions) the right hand side. After that, you get the full implication. It seems that the assumption can only be used to feed back into the right side. Is this correct?
![image](https://user-images.githubusercontent.com/11392207/60399368-caeb5a00-9b63-11e9-9d8c-18be37859ef7.png)

The following is essentially black magic to me, I don't know at all how it behaves. From this [video](https://youtu.be/F2_cUZNxUVY?t=254) it seems that you when you want to prove the output, you have to prove it for both sides of the input separately.
![image](https://user-images.githubusercontent.com/11392207/60399363-bb6c1100-9b63-11e9-8d19-4442ac2a07a2.png)

**Comment by michaelgwelch** [comment]
From the i button on the home page you’ll find several links. One leads here. https://www.joachim-breitner.de/publications/Incredible_ITP2016_preprint.pdf

**Comment by nomeata** [comment]
Did you also look at http://pp.ipd.kit.edu/uploads/publikationen/breitner16incredible.pdf ?

**Comment by nomeata** [comment]
> It seems that the assumption can only be used to feed back into the right side. Is this correct?

Correct

> when you want to prove the output, you have to prove it for both sides of the input separately.

Correct

Looks like you understand them after all :-)

**Comment by void4** [comment]
The pdf seems to be what I've been looking for, thank you for your responses. It would be great to incorporate that into some tutorial directly on the site, which would make it easier to find.

It isn't really clear to me yet why one gets these assumptions "for free", so I'll leave this issue open for now and come back later.

**Comment by nomeata** [comment]
Yeah, a good tutorial would be good, but beyond what I can invest into the program at the moment, unfortunately.
