### ISSUE TITLE
How does session 7 work?

### ISSUE THREAD

**Issue by michaelgwelch** [nomeata/incredible#126]
I've played with incredible proof machine for years but don't recall ever attempting session 7. Was looking at it now, problem 1, and have a question:

<img width="237" alt="image" src="https://user-images.githubusercontent.com/826112/94068802-4bbff280-fdb5-11ea-8915-8493fbe33a28.png">

What does the lower case `t` in `t(x)` mean? Is it semantically different than an upper case letter like `P(x)` in session 6?

**Comment by michaelgwelch** [comment]
Session 7 doesn't seem to add any new blocks and none of the blocks introduce a lower case "proposition"(?).

**Comment by nomeata** [comment]
Hmm, I think the lower case doesn't mean anything. I probabaly wrote `t` because this is the Drinker’s Paradox, and the German word is „Trinker“.

So this means the statement ought to hold for any proposition “t”

**Comment by michaelgwelch** [comment]
Thanks. That helps.
