### ISSUE TITLE
convert ascii abbreviations

### ISSUE THREAD

**Issue by mohrm** [nomeata/incredible#13]
The parser should convert ascii abbreviations into their unicode versions, so that the formulas look better. 

Plus this avoids confusion because e.g. normally one would think that you cannot deconstruct A&B with a rule which has A∧B as input, but in fact you can...

**Comment by nomeata** [comment]
The parser does that already.

What you probably mean is that the logic core should export a function that parses a proposition and returns the same proposition pretty-printed (or a parse error), and use that when printing the propositions on assumptions and conclusions. Which indeed is something we should do.

**Comment by mohrm** [comment]
Yes, this is what I mean (I hope). To illustrate:
If you add and load the following task, the UI should display "A∧A" as conclusion and not A&A:
logic: conjAndImp
assumptions:
- A
conclusions:
- A&A

I think this should also be applicable to formulas which are given by the user while proving something.
