### ISSUE TITLE
Update build instructions.

### ISSUE THREAD

**Issue by EricGT** [nomeata/incredible#130]
I have never built using a Haskell toolchain before so following the instructions. 

Then this appears.
```
Warning: The install command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-install
command or the legacy v1-install alias as new-style projects will become the
default in the next version of cabal-install. Please file a bug if you cannot
replicate a working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild
```

This is a great application and easy to use for learning Proofs. I don't know the Haskell toolchain but those that do I suspect could easily update the instructions and save others time and effort. While some are persistent and will try to figure this out, many will just walk away at this point.

Note: Please add the optional steps for installing the tools without having been installed before. In other words the instructions seem to imply the tools have been installed and just need to be updated, there are users like me who have never installed the Haskell toolchain.

**Comment by nomeata** [comment]
As you can tell, this project is quite old. At this point, I probably not only have to update the build instructions, but renovate the way this is built completely, so a larger project.

But yes, it’s probably worth fighting the bitrot…

**Comment by EricGT** [comment]
Thanks.

I ([GuyCoder](https://stackexchange.com/users/1291795/guy-coder)) don't mind doing the leg work as I will learn something. I would need someone to point me in the right direction when I get stuck. I realize this is more than several hours of work and could take a few weeks to run through some combinations or get the pieces to fit together as needed. 

This question was prompted by my question. 

[Could the Incredible Proof Machine work automatically with Metamath if rules of Metamath can be automatically translated into IPM custom logic blocks?](https://proofassistants.stackexchange.com/questions/714/could-the-incredible-proof-machine-work-automatically-with-metamath-if-rules-of)

**Comment by nomeata** [comment]
Ah, you want to import metamath proofs into the Incredible Proof Machine? Fun idea…

So far I have only thought about the other direction – generating human readable proofs, or Isabelle proofs etc. from Incredible Proof Machine proofs.

It seems that one requirement is to have an interchange format for proofs in the Incredible Proof Machine that you could target in such a tool.

**Comment by EricGT** [comment]
```
It seems that one requirement is to have an interchange format for proofs in the Incredible Proof Machine that  
you could target in such a tool.
```
Yes. As noted in the SE question, I don't know if that is a simple [term rewrite](https://en.wikipedia.org/wiki/Rewriting) and can be done all at once in a batch mode and then updated as new rules are added or does there need to be a two way active communication established because the  rules need additional information from [Metamath ](https://en.wikipedia.org/wiki/Beta_normal_form#Beta_reduction)as blocks are added.

A few other ideas, just ideas at the moment,

* Try to use the IPM to do [syntactic unification](https://en.wikipedia.org/wiki/Unification_(computer_science)#Examples_of_syntactic_unification_of_first-order_terms), then perhaps add [rules](http://www.cs.trincoll.edu/~ram/cpsc352/notes/prolog/factsrules.html), [guards ](https://en.wikipedia.org/wiki/Guard_(computer_science)) and [cuts](http://homepage.divms.uiowa.edu/~hzhang/c188/notes/ch08b-cut.pdf). 
* Another variation is what [Picat ](http://picat-lang.org/) does or SWI-Prolog does with [single sided unification](https://www.swi-prolog.org/pldoc/man?section=ssu), think [deterministic](https://en.wikipedia.org/wiki/Deterministic_system).
* Try to do [substitution](https://en.wikipedia.org/wiki/Substitution_(logic)), as the basis for [beta-reduction](https://en.wikipedia.org/wiki/Beta_normal_form#Beta_reduction) and such.
* A really for reaching idea would to be to create a toy language that uses [Hindley–Milner](https://en.wikipedia.org/wiki/Hindley%E2%80%93Milner_type_system).

I don't know how powerful the IPM is but having access to the source code, being able to build upon it and knowing unification to create new rules of inference leaves lots of possibilities open that many other tools can not touch because they don't have unification incorporated. I know you know this but other readers should know this and if not, go learn why. :-)

So at present the only way I know to get an answer to my SE question is to try and see if it works or fails and learn why. If I knew this I would not have asked the question. :-)

**Comment by nileshtrivedi** [comment]
+1 for updating build instructions. Here are the things I have tried and failed:

- Used `asdf`'s [haskell plugin](https://github.com/asdf-community/asdf-haskell) on M1 mac to install ghc v7.10.3 but ran into [this issue](https://github.com/asdf-community/asdf-haskell/issues/17) and could not install cabal.
- Used [UTM](https://github.com/utmapp/UTM) to set up an ubuntu 22.04 VM but the VM freezes when attempting graphical login
- Was able to set up Ubuntu 20.04 vm, but after adding the `hvr/ghc` ppa, I was unable to install ghc:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/19304/180193035-7baba01a-c9c9-4f0b-9d99-f5d547626c82.png">

**Comment by nileshtrivedi** [comment]
I was able to get `cabal` v2.4.1.0 working with the following:

```
asdf install haskell 8.6.5
asdf global haskell 8.6.5
asdf reshim
stack install cabal-install --resolver lts-14.27
```

Then `cabal install http://ghcjs.luite.com/master-20151222.tar.gz ghcjs-boot --no-prof` gave the error: 
```
cabal: unrecognized 'install' option `--no-prof'
```

Removing the `--no-prof` option led to this error:

```
Warning: The install command is a part of the legacy v1 style of cabal usage.

Please switch to using either the new project style and the new-install
command or the legacy v1-install alias as new-style projects will become the
default in the next version of cabal-install. Please file a bug if you cannot
replicate a working v1- use case with the new-style commands.

For more information, see: https://wiki.haskell.org/Cabal/NewBuild

Downloading http://ghcjs.luite.com/master-20151222.tar.gz
<socket: 15>: hGetBufSome: timeout (Operation timed out)
```

Because http://ghcjs.luite.com/ does not resolve any more.

**Comment by nomeata** [comment]
Yes, it's a mess. I worked on it a bit two weeks ago, and it took me a while to even compile it again. Also the CI systis broken and I had to manually deploy.

I need to redo the whole build setup, probably using nix, which will make it easier for others to get a working ghcjs etc.

**Comment by nileshtrivedi** [comment]
@nomeata Did you get a chance to revisit the build instructions? Is there a way I can help?

**Comment by nomeata** [comment]
I worked a bit on it in July, but dropped the ball again. I’m inclined to build the build system on nix, working with GHCJS is much easier there. Have you worked with nix before?

I pushed the beginnings of my work there to `shell.nix` on branch `nixify`. Maybe running `make` in a `nix-shell` already works…

**Comment by nileshtrivedi** [comment]
No, I'm in the same boat as @EricGT - never built anything with Haskell toolchain (or nix).

**Comment by EricGT** [comment]
@nileshtrivedi Nice to see others in the same boat. FYI my being able to build Incredible Proof Machine so I can add custom logics is no longer high enough on my list that I can actively work toward that end in the foreseeable future. If it becomes easy to build from source and then add a custom logic in a days time I might give it a try but for now I just keep tabs on this from afar.

**Comment by nomeata** [comment]
If you just need to add logics then I'm theory you should not need to build to code, just edit files https://github.com/nomeata/incredible/tree/master/logics.

But right now I am converting these files to JSON and concatenate them, using a tool written in Haskell…

Anyways, using nix isn't hard, so the above should work

**Comment by nomeata** [comment]
Ok, as of d3ee8b1e5dca0bd6e2bd09ff59d803b964a5da75 the build instruction in the README are updated to use nix, and we now have a CI/CD system again (using Github actions).

**Comment by nileshtrivedi** [comment]
I can confirm that I was able to build incredible on Apple M1 with the new Nix-based setup (although the `nix-build` command took more than 4 hours - even with Kaleidogen cache)! Thanks @nomeata 👏 🎉 😄

**Comment by nomeata** [comment]
Ah, yes, the cache will only have Linux artifacts. Thanks for persevering!

**Comment by EricGT** [comment]
It seems that others have taken notice of this and noted IPM on Hacker News (https://news.ycombinator.com/).
