### ISSUE TITLE
incomplete details

### ISSUE THREAD

**Issue by mohrm** [nomeata/incredible#14]
The structures shown when I click "details" lack fields, which I have to add manually.

* For graphs, I have to add the logic (otherwise loading the graph fails with an exception on the javascript console)
* For proofs, I have to add the task (otherwise "make" fails and complains about a missing task field).

Is this intended / unaviodable or should we fix this?

**Comment by nomeata** [comment]
This can be fixed, and probably should (in the code in `webui/logic.js` that fills these fields).

You might need to keep track of the name of the current task in `webui/logic.js`, though.

**Comment by nomeata** [comment]
Doesn’t seem to be too annoying, and I don’t want to start tracking the name of tasks and logics just for this feature. Punting on this for now.
