### ISSUE TITLE
deleting blocks is really weird now

### ISSUE THREAD

**Issue by mohrm** [nomeata/incredible#17]
Behaviour was observed in Google Chrome 45.0.2454.85 (64-bit)
on commit 475a265333ff2610773d614b02bbb6b7867eebbe
When I do the usual thing to delete a block, it seems like everything is selected (see screenshot). Sometimes, the block is gone, sometimes not.
![screenshot from 2015-09-16 08 41 04](https://cloud.githubusercontent.com/assets/1188377/9898046/50df2ebe-5c4f-11e5-9872-abe1e622d061.png)

**Comment by nomeata** [comment]
It works nicely for me (just drag the element far left and let go of the mouse), but maybe we are in a position to implement a hover deletion now.

**Comment by lohner** [comment]
I can confirm mohrm's observation. In Google Chrome on my machine it looks exactly like in the screenshot.
