### ISSUE TITLE
Selecting multiple blocks

### ISSUE THREAD

**Issue by nomeata** [nomeata/incredible#19]
This is a feature that is a prerequisite for a few things, such as creating new blocks while editing a proof, or moving multiple blocks at once.

**Comment by nomeata** [comment]
The UI could be shift-click, or dragging a rectangle, or both.

**Comment by nomeata** [comment]
It works with shift-click. Do we need dragging?

**Comment by gattschardo** [comment]
Shift click is nice, but only applies to blocks. If I select two blocks that are connected, it would be great if the (possible user-added) fixed connection-bends would move together with the blocks.

**Comment by nomeata** [comment]
Quite right!
