### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by nomeata** [nomeata/incredible#23]
We currently have some English and some German strings in the project. While there is not much text, we cannot do completely without text, so some form of localization is needed.

**Comment by nomeata** [comment]
A quick research revealed surprisingly little information on how to do client-side localization of HTML+JavaScript easily...

**Comment by NicoleRauch** [comment]
The Softwerkskammer platform uses http://i18next.com for localization. You can specify your strings in JSON objects and then refer to them in the JS code.

**Comment by nomeata** [comment]
Thanks, that saves me from evaluating dozens of libraries :-)
