### ISSUE TITLE
Proof blocks have absolute positions on panel

### ISSUE THREAD

**Issue by gattschardo** [nomeata/incredible#30]
Resizing the browser window can lead to parts of the proof being hidden in an invisible part of the pane because proof blocks have absolute positions (this also applies to loading proofs for e.g. grandfather from the Dev Tools in a different sized browser window). A further annoyance is that the pane isn't scrollable. Either relative positions or scroll bars will fix this -- or of course automatic (re-)layouting as in #21.

**Comment by nomeata** [comment]
The pane should be scrollable (see `rescale_paper` in `graph-interaction.js`), but the function is not called in enough situations. Usually you can fix this by wiggling the browser window.

But maybe it would be more natural to be able to drag the paper by dragging the empty space, together with zooming and maybe some indication where else things might be.

**Comment by gattschardo** [comment]
I guess I never noticed that because its hard to wiggle in a tiling WM :)
