### ISSUE TITLE
(in)consistency

### ISSUE THREAD

**Issue by mohrm** [nomeata/incredible#31]
How about
* a lesson where the student is supposed to prove False with a given consistent set of blocks? Maybe the students will then ask themselves why they fail...
* a lesson where the student is supposed to prove False with a given inconsistent set of rules? The inconsistency could be fairly subtle so you don't see it on first sight. Maybe the students could discuss then why such a set of blocks is a bad idea...

**Comment by nomeata** [comment]
The former would be ok in a guided settings, i.e. a tutorial mode that, after a while, tells the student that it is ok that it failed, or during a real-life workshop. Otherwise, people might be frustrated.

The other idea might be nice. If you have a good idea, add it!

**Comment by mohrm** [comment]
Yes, I also had kind of the same feeling with the first suggestion; I thought that it would be okay if the guide were, well, the human guide :)

**Comment by nomeata** [comment]
No immediate action required here, so removing from the list of open issues.
