### ISSUE TITLE
tell the user that there is no server-side?

### ISSUE THREAD

**Issue by mohrm** [nomeata/incredible#33]
Some users might not get that actually the whole thing just runs in their browser (for example, if they don't know what github.io is, and what it can and can't do). If they then use incredible in e.g. private mode, nothing is saved.

So wouldn't it be a good idea to tell them that, e.g. with a popup or something like that?

Of course, this only applies until there actually is a server.

**Comment by nomeata** [comment]
Well, we don’t tell the user that anything is saved in the first place :-). But it could be mentioned in the Help section.

**Comment by NicoleRauch** [comment]
Well, isn't that pretty obvious that something gets saved? If you reload the browser window and the stuff you did is still there, then it must have been saved somewhere...

**Comment by gattschardo** [comment]
On the other hand, without having a login mechanism I don't think anybody would expect this to work from a private browser window or after deleting cookies/cache (how should it?). I think it's fine mentioning it in the Help for now.

P.S.: I find re-creating the proofs quite enjoyable, I get faster every time :)

**Comment by mohrm** [comment]
On 25.09.2015 12:03, Nicole Rauch wrote:
> Well, isn't that pretty obvious that something gets saved? If you reload
> the browser window and the stuff you did is still there, then it must
> have been saved somewhere...
Yes, but couldn't it still have been saved on some server? I am no
expert in session management and cookies but isn't this possible?

> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nomeata/incredible/issues/33#issuecomment-143178684>.
> 

-- 
Karlsruher Institut für Technologie (KIT) IPD Snelting

Martin Mohr
wissenschaftlicher Mitarbeiter

Am Fasanengarten 5, Gebäude 50.34, Raum 022
76131 Karlsruhe

Telefon: +49 721 608-48352
E-Mail: martin.mohr@kit.edu

http://pp.ipd.kit.edu

KIT - Universität des Landes Baden-Württemberg und
nationales Großforschungszentrum in der Helmholtz-Gemeinschaft

**Comment by mohrm** [comment]
On 25.09.2015 12:06, Richard Molitor wrote:
> On the other hand, without having a login mechanism I don't think
> anybody would expect this to work from a private browser window or after
> deleting cookies/cache (how should it?). 

You and I know that it does not work, of course. But others might not
think much about that. Why should they? They open the browser, visit the
page and it works. They don't care whether something is stored on a
server or in their browser store. So it would only be fair to tell them
that their stuff is stored locally.

> I think it's fine mentioning it
> in the Help for now.
Fine with that.
> 
> P.S.: I find re-creating the proofs quite enjoyable, I get faster every
> time :)
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nomeata/incredible/issues/33#issuecomment-143179665>.
> 

-- 
Karlsruher Institut für Technologie (KIT) IPD Snelting

Martin Mohr
wissenschaftlicher Mitarbeiter

Am Fasanengarten 5, Gebäude 50.34, Raum 022
76131 Karlsruhe

Telefon: +49 721 608-48352
E-Mail: martin.mohr@kit.edu

http://pp.ipd.kit.edu

KIT - Universität des Landes Baden-Württemberg und
nationales Großforschungszentrum in der Helmholtz-Gemeinschaft

**Comment by gattschardo** [comment]
Updated help in 3222cb8ad5bea0cd86eac6e9d2f62655acbb67ec
