### ISSUE TITLE
Cannot acces top right port in 'v' widget

### ISSUE THREAD

**Issue by alanz** [nomeata/incredible#34]
![noaccess](https://cloud.githubusercontent.com/assets/409607/10099602/6ccdc19c-638b-11e5-87b2-e435f1ace5ff.png)

As per the attached image, as soon as the mouse moves near the connection port at the top right the big red X comes up, obscuring it

**Comment by alanz** [comment]
Wow. Fastest bug fix I have ever seen :)

**Comment by nomeata** [comment]
Thanks for opening an issue; this is a very annoying problem. I don’t have a good solution (i.e. one that consistently works well with all blocks), but I guess I should apply a hotfix to amend this.

**Comment by alanz** [comment]
Maybe just make the block wider, so both can show?

**Comment by alanz** [comment]
Having it always show up outside the block to the top right as with you fix
should work consistently?

**Comment by nomeata** [comment]
I’m worried that it might be too close to the `A` output of the ∧ elimination rule.
