### ISSUE TITLE
Bug with helper blocks

### ISSUE THREAD

**Issue by thomie** [nomeata/incredible#35]
After dragging a helper block onto the board, it can not be deleted and a weird second copy shows up in the topleft corner. After clicking "switch task", the undeletable helper block also shows up there, and it isn't possible to go back to the previous task.
![incredible-helper-block-bug](https://cloud.githubusercontent.com/assets/157521/10107942/9c9e4df0-63be-11e5-9e53-4f78f1c3da0c.png)

Occurs both in latest firefox as chrome on Ubuntu.

**Comment by hestad** [comment]
On Windows here, seeing the same for latest Chrome/Firefox/IE Edge
