### ISSUE TITLE
FR: Narrow the list of available building blocks based on what is possible

### ISSUE THREAD

**Issue by jwiegley** [nomeata/incredible#37]
For example, if I hover my cursor over the output port of a block on my canvas, grey out all available blocks (both to the left, and elsewhere on the canvas) which cannot be connected to from that port.

@nomeata This is an amazing idea!  I'm always excited to see creative thinking in the arena of better UI and tooling for proof environments.

**Comment by nomeata** [comment]
Nice idea, although it might give away too much. And actually be tricky (and costly) to implement... I’ll defer that for now.

**Comment by nomeata** [comment]
In the interest of having a short list of open issues, I’m closing this, marked as “would be nice”.
