### ISSUE TITLE
How do I remove an arrow?

### ISSUE THREAD

**Issue by polkovnikov-ph** [nomeata/incredible#38]
I see no obvious way to remove an arrow. Currently I find this the hardest part of the quest.

**Comment by nomeata** [comment]
With arrow, do you mean a → or a connection between blocks?

**Comment by polkovnikov-ph** [comment]
@nomeata I've meant connections between blocks. I've found that `(X)` that appears if one hovers over an arrow or a block for a while. This should certainly be documented or changed to something more obvious like block selection and `delete` button.

Also editor has very low contrast on my monitor. It is not set to sRGB mode (well, there's no sRGB mode on it), so it's OK to get bad image, but I don't think there're a lot of people that have monitor properly set up. Would it be possible to change the color of blocks into something much more contrasting than dim gray, e.g. midnight blue from here (https://flatuicolors.com).

**Comment by nomeata** [comment]
I find the “delete button appears on hover” interface quite intuitive, as there is otherwise no notion of selecting connections, I’m not sure if that’s the best way to go.

The colors could generally use some improving, I guess.

**Comment by nomeata** [comment]
The delete interaction is provided by JointJS, so in the interest of time I don’t think I’ll change that, until more people complain about that part.

I would love if someone who knows something about visual design could choose the colors, though.
