### ISSUE TITLE
Any plans on extending the system?

### ISSUE THREAD

**Issue by polkovnikov-ph** [nomeata/incredible#39]
I'm not a big fan of Coq and such languages, because these have quite heavy syntax and the learning curve is not very good (i.e. I'm just not smart enough). Though there's a lot of interesting logic systems that I would love to play with, apart of BHK:

 - There're (iso)recursive types that require just two operations to implement, though I'm not sure if these are OK for a proof system.

    pack : forall p. (mu x. p x) -> p (mu x. p x)
    unpack : forall p. p (mu x. p x) -> (mu x. p x)

 - Dependent types that are, as I can guess, not that easy to implement.
 - Notions of equality.

Do you have any plans on extending the system? Would it be possible to allow users define their own blocks to model such systems?  Something like "propositions" in Agda, which are essentially fake proofs for any given fact, would fit into this role.

**Comment by nomeata** [comment]
You can probably do a lot simply by defining your own logic, i.e. specify the rules that you want to use with your custom symbols or binders.

So if you want to play with µ, clone the repository, add a new logic to the `examples/logics` folder, add some example tasks to `session.yaml`, run `make` and there you go. If you want to be able to write `µx.P(x)` instead of `µ(λx.P(x))`, as you would now, you have to let the parser in `Propositions.hs` know that `µ` should parse as a binder.

**Comment by nomeata** [comment]
(I’m closing this, as this is not an actionable bug report or feature request. Of course, this can still serve as a discussion form here; I just want to keep the list of open issues tidy.)

**Comment by nileshtrivedi** [comment]
Commenting on this issue 7 years later :)

What would it take to implement [Dependent Type Theory](https://leanprover.github.io/theorem_proving_in_lean4/dependent_type_theory.html) similar to Lean's?

In Incredible Proof Machine, I'd like to be able to prove theorems about natural numbers or abstract algebraic structures like Group, Field and Vector Spaces. Can I get there just by adding new logic rules or do I need to modify Haskell code itself?

**Comment by nomeata** [comment]
If you can describe the logic via natural deduction rules it should be possible to some things just by defining your own logic, similar to the existing STLC rules
(https://github.com/nomeata/incredible/blob/master/logics/STLC.yaml). It will get unwieldy. 

For a dependent type system, to make it a bit more practical, one could imagine changes to the UI. For example, often some arguments of a function can be inferred, so it would be good if you didn't have to specify them using blocks.
