### ISSUE TITLE
Connections can be created the “wrong way”

### ISSUE THREAD

**Issue by nomeata** [nomeata/incredible#4]
and it confused the logic. I now made the logic complain about it, but it would be nice if the UI automatically oriented the links the right way.

It might be possible to detect a wrongly-oriented link in `graph.on('change:source change:target')` and reverse it there.

@olydis, since you already worked on the UI code, do you think this is easily possible?

**Comment by olydis** [comment]
Proposal: https://github.com/olydis/incredible/commit/84fa0dd1feed341792a23fb9816c0ea1297ab735

I did not handle the problem in `graph.on('change:source change:target')`, it might be pretty hard (and hacky) to reverse a link *while it is dragged* without messing up some internal state. (I have not tried, though.)

Instead, I simply normalize the data during proof construction. Possible disadvantage: should we ever style links in an asymmetrical way, it would still look reversed!

Assumptions I made: Links are only allowed from `direction=out` to `direction=in` magnets - is that right?

Also, is there a better way to retrieve magnet properties than by navigating to the DOM-element (see the jQuery-magic I used)? I'm having a hard time finding anything useful in the joint-js docs.

**Comment by nomeata** [comment]
> Instead, I simply normalize the data during proof construction. Possible disadvantage: should we ever style links in an asymmetrical way, it would still look reversed!

I actually tried that way first, but I fear it will break the display in case unification fails, and different propositions are printed on top of the various ends of the connection.

So either the connection needs to be reversed after all, or the display code needs to take that into account.

> Assumptions I made: Links are only allowed from direction=out to direction=in magnets - is that right?

Yes, this is also what is (or should be) enforced by `validateConnection`.

> Also, is there a better way to retrieve magnet properties than by navigating to the DOM-element (see the jQuery-magic I used)? I'm having a hard time finding anything useful in the joint-js docs.

http://www.jointjs.com/api#joint.dia.Paper:findViewByModel might alleviate some of the pain, but not all. Are you on StackOverflow? There is a `jointjs` tag there, and the jointjs author seems to be sometimes active there, so you could try to get some help there.

**Comment by olydis** [comment]
> Yes, this is also what is (or should be) enforced by `validateConnection`.
Wait, so would actually *preventing* the creation of wrongly oriented links be an option? So that users are simply not able to drag from inputs to outputs?

**Comment by nomeata** [comment]
This is how it’s done in http://www.jointjs.com/demos/logic, but I’d consider that bad UI design: While proving, I often think backwards from the goal, and I want to draw my proofs this way.

Also, it sometimes is useful to create an otherwise unconnected connection just to see what proposition is printed on it.

**Comment by olydis** [comment]
I agree, that's exactly how I used it when playing around! I'm also in favor of allowing it, was just confused about "_this is also what is (or should be) enforced by validateConnection._".

Okay I'll look into swapping directions (on mouseup or something) later tonight!

**Comment by nomeata** [comment]
mouseup might not be enough, after all the logic is run even while the mouse is dragged.

You should try to see what breaks if it happens in `graph.on('change:source change:target')`. But you are probably right that it will break things...

I’ll post this on stackexchange.

**Comment by nomeata** [comment]
http://stackoverflow.com/questions/32232786/ensure-orientation-of-jointjs-connection

**Comment by olydis** [comment]
Nice, thanks! I have played around further a little bit, trying to surgically swap values from within `graph.on('change:source change:target')` - but without luck, yet... it is quite hard to track down all the places the library spills state that need to be changed (sometimes closed over by anonymous functions). Hoping for an amizing library-function that we managed to miss...

**Comment by nomeata** [comment]
Or maybe we just have to byte the bullet and swap the values in `buildProof`, as in your original patch, but then also when reading data coming out of the proof. Maybe be better than fighting the library.

**Comment by nomeata** [comment]
More information if someone else wants to tackle this: There are two possible ways to detect the “correct” orientation. 
 * You look at the direction attribute of the magnet¹, which can be either "in" or out".
 * You derive the direction from the logic model. [This code](https://github.com/nomeata/incredible/blob/0d5c75bc88e8615eea61454d96a00cc67dc841ec/webui/logic.js#L337) accesses the port-specific model data from a `{id: ..., [port: ...]}` object. Conclusions are always `in` ports, assumptions always `out` ports, and for the others, you have to look it up in the `logic` data structure.

I can elaborate if you find problems.

¹ JointJS name for the bit of the SVG that represents the element where connections can be docked onto.
