### ISSUE TITLE
Logics Blocks variable mismatch

### ISSUE THREAD

**Issue by Zannick** [nomeata/incredible#42]
The two logics blocks introduced in Session 6 that have "P(c)" do not work as labeled. The first should take P(c) and produce ∀x.P(x) but instead produces ∀x.P(c). The second should take ∃x.P(x) and create an assumption P(c) but instead creates an assumption P(c_k) that conflicts with P(c).

I believe this makes Session 6 impossible, as well as the custom task "∃x.P(x)→⊥ / ∃x.P(x)→Q" (which is similar to the simple proof for "A→⊥ / A→B"):

![Screenshot showing the variable mismatch](http://i.imgur.com/GphI66C.png)

(Funny enough, if I change box 11 to P(x), then box 14 produces ∀x.P(x) which still disagrees with the label ∀x.P(x) from box 15.)

**Comment by gleachkr** [comment]
Are you sure this is not the intended behavior? If I'm reading it correctly, it looks like your desired subproof would establish "Everything is P" from the premise "Something is P".

**Comment by Zannick** [comment]
The symbolism leads me to believe that the intention is to provide "∃x.P(x)" and show "P(c)→Q" to establish Q. I assume P(c) to be an expression with a free variable c, based on the "generalization" block that is stated to perform "P(c) → ∀x.P(x)". Q is an expression without c. (Perhaps some actual description could be added to the help page...) So really, my subproof is trying to establish Q from the premise "Everything is P" in order to establish Q from "Something is P".

If this isn't the intention I have no idea what to do with the only block that consumes existence statements.

**Comment by nomeata** [comment]
With local variables (e.g. the `c` and `y` in these blocks) there are a few things happening that are not visible from the UI, but I believe it is logically the right thing.

The `c` in the the ∀ introduction block is not a free variable, but a local constant: It will not unify with anything else but `c`, nothing special is known about it, but also only free variables “on the left” of the block may refer to it. In particular, the `P` from the block may not.

Similarly, the `c` in the elimination block for `∃` is a constant, and it is only valid “inside” the “dent” of the `∃` block – in particular, `Q` may not refer to it any more.

Does that explanation help you?

**Comment by Zannick** [comment]
I believe your explanation matches my view of things, but:

if the `P` on the right of the `∀` introduction block is not supposed to reference `c`, then why does it? That is essentially my question here: how do I eliminate `c`? The `∀` introduction block does not. (Perhaps I am violating one of the restrictions of universal generalization but it is really hard to tell...)

Your comment about `c` and `y` made me realize that the `c` in the `∃` elimination block is in the fact supposed to be the `y` that "exists", and thus I managed to eliminate the `c` with the `∃` introduction block that accepts `P(y)`.

So I guess the apparent notational distinction between `c` and `y` confused me. I interpreted `x` as a **bound** variable, `y` as a **fixed** variable (constant), and `c` as a **free** variable, this latter based on the `∀` introduction block. The `∃` elimination block should have `P(y)`, not `P(c)` under that interpretation. I suppose if I go reread https://en.wikipedia.org/wiki/Universal_generalization I get less convinced these last two are really different... At least using `P(y)` in this case would suggest that universal generalization isn't valid in this case.

It also doesn't help that the UI fights me during proof construction (as the `c`s cannot be renamed):
![Almost complete proof still has error](https://cloud.githubusercontent.com/assets/518709/10124894/b5634468-6516-11e5-89d5-b8e33c543d48.png)
(If I connect the last two, the `y_12`s are replaced with `c_3`s and the proof is marked solved. Note there's no way to type subscripts in the helper block.)

**Comment by gattschardo** [comment]
Note that while you cannot type indexed constants, you can use the helper block to rename them::

![exe-unification](https://cloud.githubusercontent.com/assets/233331/10125321/d76d423a-656f-11e5-8019-20602c74bdbe.png)

You are right tough, the unifier does behave badly on partial proofs using these quantifiers, e.g. I have no idea how it came up with the labels on the red line sticking out to the left.

**Comment by nomeata** [comment]
> Note that while you cannot type indexed constants, you can use the helper block to rename them

Not really. It makes it unify `P(c)` with `Q(k)`. But `c` is a locally scoped variable not occurring on the other side, so it instantiates `P = λc.Q(k)`, i.e. a constant predicate. Usually _not_ what you want.

There needs to be a way to reference these locally bound constants. Maybe I should simply parse `c1` as `c₁`, and thus disallow variable names with numbers? But I’m worried that soundness can easily be broken when you can arbitrarily reference local constants, and need to think about what that entails.

**Comment by nomeata** [comment]
> So I guess the apparent notational distinction between c and y confused me. I interpreted x as a bound variable, y as a fixed variable (constant), and c as a free variable, 

My informal convention is: Upper case variable: Free predicate. Lower case `x`: Variable bound within the same proposition. Lower case `y`: free variable (i.e. can be instantiated with any term). Lower case `c`: locally scoped constant (i.e. cannot be instantiated, other free predicates and variables may not mention it).

Note that if it says `P(c)`, then you can instantiate `P = λa. Q(a)` to get `Q(c)`, but still `P`’s instantiaion  does *not* reference `c`.

**Comment by lohner** [comment]
Perhaps we could add some markup/color to the propositions, such that free and bound variables as well as locally scoped constants become more distinguishable.

One could then even try to visually "group" a locally scoped constant with it's generating block (e.g. by flashing, whenever one hovers over the corresponding constant and/or block). However this requires a richer term structure on the javascript side.

**Comment by nomeata** [comment]
Nothing concretely actionable in this issue, so I’m removing it from the list of open issues. Discussion can continue, and concrete tasks can be filed as individual issues.
