### ISSUE TITLE
Is master compatible with ghc 7.10.2 ?

### ISSUE THREAD

**Issue by DeepSpawn** [nomeata/incredible#44]
So have followed the instructions in the README in an attempt to get it building locally. The current version of GHCJS requires a newer version of GHC than the version mentioned in the repo. So I am using the following 

'$ ghcjs --version
The Glorious Glasgow Haskell Compilation System for JavaScript, version 0.2.0 (GHC 7.10.2)`

I am trying to build the master branch, commit 1eac53c9635d26bca4aa08d2b81138cff84d5adf
The compilation error I get (when running make logic.js) is as follows,

>[1 of 2] Compiling ConvertJS        ( js/ConvertJS.hs, dist-ghcjs/build/js-interface/js-interface- >tmp/ConvertJS.js_o )
>
>js/ConvertJS.hs:14:25: Not in scope: ‘castRef’
>
>js/ConvertJS.hs:21:25: Not in scope: ‘castRef’
>
>js/ConvertJS.hs:28:25: Not in scope: ‘castRef’
>
>js/ConvertJS.hs:37:14: Not in scope: ‘castRef’
>make: *** [logic/dist-ghcjs/build/js-interface/js-interface.jsexe/all.js] Error 1

Have I made a mistake somewhere or is this a real compilation error? (This is on a clean Ubuntu install so there should not be anything else causing problems)

Cheers,
Gene Taylor

**Comment by nomeata** [comment]
@gattschardo runs this with GHC-7.10. My guess would be that GHCJS has changed in incompatible ways. Too bad that [they do not do releases yet](https://github.com/ghcjs/ghcjs/issues/19).

Maybe they have merged the `improved-base` branch into maste?

Can you try to check out revision `c1b623` of GHCJS and see if it works with that?

**Comment by nomeata** [comment]
Or even better: Try branch [old-base-ghc-7.10](https://github.com/ghcjs/ghcjs/tree/old-base-ghc-7.10) of GHCJS.

**Comment by nomeata** [comment]
And read https://github.com/ghcjs/ghcjs/tree/old-base-ghc-7.10#build-the-libraries about what flags you have to pass to ghcjs-boot to get going. Sorry for the hassle, but GHCJS is quite a young technology.

**Comment by gattschardo** [comment]
For the record, I use

* ghcjs [this commit](https://github.com/ghcjs/ghcjs/commit/8c35cc8631dda184bcbf29ee34bfc7cd1b656edd)
* ghcjs-prim [this commit, still HEAD](https://github.com/ghcjs/ghcjs-prim/commit/bd83ce26f7e32fa9dc6c762d05ca595589d7b1a3)
* haddock-internal [this commit, still HEAD](https://github.com/ghcjs/haddock-internal/commit/47758773d6b20c395a1c76a93830070fde71dbab)

and GHC 7.10.**1** to build successfully. So I suggest using the older ghcjs commit, if that doesn't fix it, the incompatibilty must be between 7.10.1 and 7.10.2.

**Comment by nomeata** [comment]
I strongly doubt that it’s 7.10.2 vs. 7.10.1, as it is clearly a change in the ghcjs libraries.

**Comment by nomeata** [comment]
@DeepSpawn, did you have success with the instructions on https://github.com/ghcjs/ghcjs/tree/old-base-ghc-7.10#build-the-libraries?
