### ISSUE TITLE
Zoom and center toolbar

### ISSUE THREAD

**Issue by nomeata** [nomeata/incredible#45]
The paper needs a small toolbar in the corner, similar to the toolbar of the main page, with functionality for
 
 * zooming out (and back in)
 * zooming and panning the proof to fit.

**Comment by lohner** [comment]
Added some basic zoom functionality in c2c164ad43d95a7379f3693b514ae219bf2b6f27 . Controls are on top in the left pane. Zoom-in/-out and 1:1 is relative to the middle of the current viewport. 'Fit' centers and fits the complete graph.

Is anything else missing? Or do you want something changed?

**Comment by nomeata** [comment]
I’d put the toolbar in the top-right corner of the paper, but I can do that myself.

Why don’t you use the second parameter of `scale`, where you can specify the origin of the scaling? Might make the code simpler: http://www.jointjs.com/api#joint.dia.Paper:scale

**Comment by lohner** [comment]
> Why don’t you use the second parameter of scale, where you can specify the origin of the scaling? Might make the code simpler: http://www.jointjs.com/api#joint.dia.Paper:scale

I'd tried that. But wasn't able to figure out in which coordinate system i have to specify the origin of the transformation.

**Comment by lohner** [comment]
I factored out scaling relative to a point in bc30c8af5c79a2f02665ab6da07f6d9ca21e412c. The point must be given in pixel coordinates relative to the top left corner of the viewport. E.g. `(paper.options.width / 2, paper.options.height / 2)` for the center.

**Comment by lohner** [comment]
Added zooming by using the mouse wheel in 9dd6b08f040c55a34a8fb6c87bcad9ece7b4a588.

**Comment by nomeata** [comment]
> The point must be given in pixel coordinates relative to the top left corner of the viewport. E.g. (paper.options.width / 2, paper.options.height / 2) for the center.

That’d be useful information to have as a comment in the code :-)

**Comment by lohner** [comment]
> That’d be useful information to have as a comment in the code :-)

That's right :) Added in eb5cb72fe7206f6016ed733a07c9517f3b85cb6d.

**Comment by nomeata** [comment]
This is complete, isn’t it?

**Comment by lohner** [comment]
I think so.
