### ISSUE TITLE
Question: How do I use lambdas?

### ISSUE THREAD

**Issue by ratefuchs** [nomeata/incredible#49]
On http://incredible.nomeata.de, there seems to be neither documentation nor examples how to use lambdas.

**Comment by nomeata** [comment]
Lambdas are used internally to represent binders and instantiations; I’m not sure if there are good use cases for them. I guess should simply remove them from the Help...

In fact, arbitrary lambdas are dangeous, see https://www.reddit.com/r/haskell/comments/3m7li1/the_incredible_proof_machine/cvcqynk
