### ISSUE TITLE
Better pretty-printing

### ISSUE THREAD

**Issue by nomeata** [nomeata/incredible#5]
The current printing code for propositions in the logic core is too simle, and should avoid unnecessary parentheses.

**Comment by gattschardo** [comment]
Fixed in f569196d7cca88b4067d2ae56da1deabbe14cedf, though to further tweak it if there are any suggestions

**Comment by nomeata** [comment]
Thanks. Seems to work, although it does not take precedence into account (but maybe that is a good thing):
```
*Propositions> putStrLn $ let Right prop = parseTerm "a∧b∨c" in printTerm prop
(a∧b)∨c
```

It is a bit unorthodox to use trees here (instead of just concatenating list-building functions). If you are curious about a more “proper” way of doing it, maybe https://www.haskell.org/onlinereport/derived.html#sect10.4 is helpful.

**Comment by nomeata** [comment]
Fixed somewhere along the way.
