### ISSUE TITLE
Option to fully parenthesize?

### ISSUE THREAD

**Issue by FranklinChen** [nomeata/incredible#52]
For pedagogical purposes, I'd like to suggest an option to fully parenthesize expressions, because newcomers to logic (I'm considering showing this cool app to kids!) may get distracted by matters of precedence of the operators.

**Comment by nomeata** [comment]
We thought about not making use of associativity when printing term, but to fully parenthesize might be overkill – I don’t want to turn this into a tutorial on reading lisp :)

Also, I will be very careful with addition options, as these have a relatively high maintenance cost, and rather try to find something that works well for everyone.

**Comment by nomeata** [comment]
(Tagging as UI, although the code in question is in the Haskell part.)
