### ISSUE TITLE
Undo/Redo

### ISSUE THREAD

**Issue by nomeata** [nomeata/incredible#53]
We really should provide undo/redo functionality. It should be relatively easy: Maintain a list of serialized graphs (`graph.toJSON()`) that is appended upon major changes, and cleared when a new task is loaded, and popped upon undo.

**Comment by lohner** [comment]
I started implementing this (see branch undo_redo, 8870711159a3412f75b1e2931288b8531680e4ed).

For now, simple undoing (managed by a list) is implemented. The saved state consists of the current graph, the zoom factor and position of the paper.

However I am not sure when to save the current state. At the moment it is saved whenever one clicks the paper or uses the mouse wheel on the paper. Unfortunately this misses some importent actions, e.g. dragging a new block on the paper or deleting a block.
I also tried experimenting with `graph.on('change', ...)`, but this leads to way too many save points.

Ideally the state should be saved once, whenever there is a visual change in the paper that was triggered by one user action. (More difficulties arise by defining *one* user action. E.g. zooming with the mouse wheel triggers several consecutive Javascript 'wheel' actions - in my opinion these should be combined to one user action).

Any thoughts on this?
