### ISSUE TITLE
make block area resizable

### ISSUE THREAD

**Issue by mohrm** [nomeata/incredible#56]
If the block area would be resizable horizontally, it would be possible to see all the blocks.

**Comment by nomeata** [comment]
With block area, do you mean thr left pane?

**Comment by mohrm** [comment]
yes :-)

**Comment by nomeata** [comment]
I still don’t follow. You can scroll vertically to see all blocks. Did you mean “to see the whole block”, for blocks with long propositions?

The bug that the first generated custom rule is not centered properly is known.

**Comment by mohrm** [comment]
With "horizontally", I indeed mean that I want to make the width higher. Vertical scrolling lets me see all the blocks, but I cannot see all of the widest block.

**Comment by nomeata** [comment]
Ok, got it :-)

Certainly needed, although it’s tricky to get that while still having the blocks nicely aligned vertically.

**Comment by nomeata** [comment]
Fixed in ef0d8393
