### ISSUE TITLE
invalid proof recognized as valid

### ISSUE THREAD

**Issue by sdx23** [nomeata/incredible#62]
Playing around I got this:

http://i.imgur.com/isU5wfH.png

If I'm understanding correctly this is a logic bug, as A is coming out of nowhere.

**Comment by sdx23** [comment]
Ah, i see my mistake. Ignore me and continue whatever you were doing :)

**Comment by nomeata** [comment]
:wink: Have fun

**Comment by sdx23** [comment]
Thanks - also for the great work. It's highly addictive :)

**Comment by nomeata** [comment]
> It's highly addictive :)

I didn’t expect that to be the case so much, but it makes me very happy.
