### ISSUE TITLE
custom tasks with multiple assumptions/conclusions

### ISSUE THREAD

**Issue by mohrm** [nomeata/incredible#66]
How do you make custom tasks with multiple assumptions and/or conclusions?

I can't find anything in the help about that, tried different separator chars like ' ', ';', ',', but none worked. I also tried to find the code which parses custom tasks but could not really find it. I still don't know whether it is original javascript or original haskell code. I found this javascript function "incredibleProofTerm" but its definition lies within a generated js file and I can't find the corresponding haskell function *confused*

Is this actually supported? 
if yes:
* what is the separator char?
* should be mentioned in the help section

if no:
* okay, then I have to circumvent it (using &)
* should be mentioned in the help section

**Comment by lohner** [comment]
Just write them in seperate lines above and beneath the ---------- separator. Could definitely be mentioned in the help dialog.

**Comment by mohrm** [comment]
Ah, so the separator char is '\n'
thanks :)

**Comment by mohrm** [comment]
fixed in 0361c694dfdb3ad57de2b6d89e28e5dd430dc2a9 and thereby closed
