### ISSUE TITLE
Pretty-printer captures constant

### ISSUE THREAD

**Issue by Rokhan** [nomeata/incredible#69]
Hello,

It seems like a bug to me but it could also be a misleading display of error with a wrong proof.

![incredible-proof__bug](https://cloud.githubusercontent.com/assets/10841363/10531552/a01703dc-73b3-11e5-96e0-997b19120c96.png)

Thanks for this software, it's *incredibly* fun.

**Comment by nomeata** [comment]
Indeed, this is a problem in the printing of propositions: The left term on the red connection should be something like `∀x₁.P(x)`, i.e. the bound variable is different from the one in `P`.

> Thanks for this software, it's incredibly fun.

Thanks!
