### ISSUE TITLE
I don't quite understand the rules for quantification

### ISSUE THREAD

**Issue by michaelgwelch** [nomeata/incredible#71]
I was able to complete all of the proofs involving quantification except for one. I find I don't quite understand a few things. (If these could be clarified in the info box that'd be great)

1. The difference between a `c` and a `y` in the rules that introduce universal and existential quantifiers respectively. Obviously the `c` must somehow capture the fact that this value was completely arbitrary and therefore if `P(c)` is true then it must be true for all values.

2. How does one "generate" a `c` or I guess I should say a `P(c)` so that you may prove a universal. None of the rules produce a `P(c)` only a `P(y)` and I'm assuming there's a difference. (Hmm, not quite right. I see one of the existential rules let's you assume a `P(c_v)` (where v is a subscript) within the context of the block. So I guess that's a hint for me.

3. I've been able to complete all of the proofs involving quantification except for the last one. I've tried many different approaches. The image below captures one approach I took which I really didn't think was going to work. But even though I didn't think I was on the right track, I found it interesting that if you look at the image you can see that it appears (incorrectly) that I'm really close. The output of the -> elimination  block is an `A`. The desired conclusion for the -> introduction block is `A`. So it would appear that I could just hook those two up and be done. However if I actually connect these two, then it is revealed that I have some unification errors. Why are there no errors prior to connecting them?
<img width="924" alt="almostproved" src="https://cloud.githubusercontent.com/assets/826112/11769355/cbac3786-a1aa-11e5-9160-16134747c819.png">

The errors become apparent when I make the connection.

<img width="919" alt="nopenotgoingtowork" src="https://cloud.githubusercontent.com/assets/826112/11769381/9a8071e4-a1ab-11e5-809e-a4cb232788fb.png">

By the way, I'd appreciate a hint on this one. Been struggling for 2 days now and while on paper this proof seems trivial, I can't "solve the puzzle" using the tool.

**Comment by michaelgwelch** [comment]
Another approach I took was to use `TND` to generate (!x.P(x)) v ((!x.P(x))->False). The first case is trivial, but I can't seem to make any progress with the second case.

I also used `TND` to just assume for some value (P(y)) v (P(y) -> False). With this start I can make progress with the second case but don't make any progress with the fact that (P(y)) unless I could somehow use it to prove the universal.

**Comment by nomeata** [comment]
Indeed the quantification mechanism is not very well documented, and also not presented in the UI as good as I’d like it to be.

1. `c` are constants, e.g. they only unify with themselves. `y` are free variables: They will unify, if needed. So if you connect `P(y)` with `P(f(c))`, this works (and `y` becomes `f(c)`), but connecting `P(c)` with `P(c₂)` will not work.

2. To prove `∀x.P(x)`, you will have to prove `P(c)` for some arbitrary `c`; that’s what the ∀-introduction block is for. The subscript indices the block that introduced a certain constant (`c₂`) or free variable (`y₂`).

3. This proof will not work without the TND block, as it is a theorem only in classical logic. In your dead end proof attempt, the problem is that you may use `c₅`, the “arbitrary constant” of the ∀-intro-block, only in the part of the proof that enters that block, but nothing “to the right of it”. In a partial proof, the system cannot always know what wil end up to the right of it. You can see that `c₅` may not occur there because the free variable is written as `y₃`, and not `y₃(c₃)` (read: `y₃` is any expression and may depend on c₃). If you have seen more standard rule inference: This corresponds to the “`c` free in the context” requirement of the ∀-introduction-rule.

Using TND should get you further. Here a hint: Make sure you use the ∃-intro-block inside the case analysis block, once above and once below the line. Do _not_ just put it once at the very end, directly connected to the conclusion.

**Comment by michaelgwelch** [comment]
Thanks. The note about the subscripts being related to the block that introduced them is good to know. Also good to know that constants cannot unify with something else.

Regarding your point 2: So even though no rule will produce a `P(c)`, if I produce a `P(y)` it can unify (if appropriate/needed) to `P(c)` for use in a ∀-introduction  

I really like this tool. Thanks for your work.

**Comment by michaelgwelch** [comment]
@nomeata Thanks for the hint. Am I using TND appropriately? If so, I find the first case trivial. I find the second case quite hard. Makes me think that perhaps I'm still on the wrong track.

In the second case I have (∀x.P(x)) -> False. My thought is that to do anything with that fact, I need to prove (∀x.P(x)), and from there I can prove anything. But as I've alluded to above, I have not had any success in using the ∀-introduction rule.

**Comment by nomeata** [comment]
You are on the right track! This is a very tricky puzzle indeed, and you might have to use TND a second time.

**Comment by michaelgwelch** [comment]
Thanks for taking the time to reply to this question. (I feel like I should start a question on stack exchange mathematics to discuss this. Perhaps that would be a better place.). I did indeed start a second TND. Here's a screen shot. (I can delete these comments in the case that I'm close and giving away the answer for others).

I'm not sure I'm generating the correct fact with this second TND. As I'm left with two pieces of data that don't seem to me to actually infer the conclusion. I have that P(y_10) and that (∀x.P(x)) -> ⏊ . 

<img width="922" alt="anothertnd" src="https://cloud.githubusercontent.com/assets/826112/11783773/8761cb56-a23e-11e5-9928-ff338020fb8e.png">

Here's a sketch of the proof that I think I'd like to do. Given that (∀x.P(x)) -> ⏊ show that ∃x.P(x) -> ⏊, from there it's easy to prove the conclusion (I think).

**Comment by michaelgwelch** [comment]
It seems this question is more appropriate for a Q&A site and not your issues tracker. I've "moved" it http://math.stackexchange.com/questions/1575982/would-like-a-hint-for-this-graphical-proof-exercise-on-the-incredible-proof-mach

**Comment by michaelgwelch** [comment]
My assessment that a Q&A site was a more appropriate place is being questioned as one reviewer has voted to close the question. Oh well.

**Comment by nomeata** [comment]
StackExchange can sometimes be a bit picky about what they allow. But we managed to establish [Isabelle](http://isabelle.in.tum.de/) questions on StackOverflow, so there is precedent.

If they really send you into exile, there is a classical old-school [mailing list](https://lists.nomeata.de/mailman/listinfo/incredible). I will come back to you, but not today.

**Comment by lohner** [comment]
I had a quick look at your proof attempt @michaelgwelch and your hand written proof sketch on StackExchange:

They only coincide in the first step of the case analysis on ∀x.P(x).
In the second step you correctly sketch, that it follows, that there is a c with ¬P(c). However in your incredible proof you try to directly conclude that ∃x.P(x)→A.

You could use the helper block (the on with the pencil) to try to conclude ∃x.P(x)→⊥ first, as you stated in your proof sketch. This is possible with the assumption (∀x.P(x))→⊥ by using two times "proof by contradiction". From there on it is rather simple to eventually get the conclusion of the task.


SPOILER ALERT: I used a few custom blocks to solve this task (mainly case analysis ♛ and proof by contradiction ☏). However, the main difference to your approach is, that I didn't do a case analysis on ∀x.P(x), but on A instead:

![incredible-proof](https://cloud.githubusercontent.com/assets/1277734/11805974/1fda3f72-a310-11e5-9eca-51477d34dab0.png)

**Comment by michaelgwelch** [comment]
@lohner thanks for taking the time to review this in both forums. You are correct in observing that my graphical proof doesn't follow the hand-waving proof. I got stuck trying to derive ∃x.P(x)→⊥. Your hint to try using proof by contradiction (twice) is appreciated. Thanks for the spoiler alert. I'm avoiding looking at your solution for now.

**Comment by michaelgwelch** [comment]
@lohner I finally had to break down at look at your proof. I see the use of your custom "proof by contradiction" block. I've been trying to do this without such a block. Is it possible? In other words, are the current set of blocks sufficient to derive a proof by contradiction? I can't figure out how.

How does one create a custom block? Write the appropriate javascript?

**Comment by nomeata** [comment]
@michaelgwelch Custom blocks are just representatives of groups of regular blocks, so yes: it is possible to recreate his proof using just the basic blocks.

To create your own custom blocks, select multiple blocks (using shift-click) and then on the left, you see a preview of the new block and a button to add it.

**Comment by michaelgwelch** [comment]
Oh that is cool! Like so many things it seems simple when you understand it. I now have my own custom proof by contradiction block.

**Comment by michaelgwelch** [comment]
You can mark this closed. I was successful in completing this proof. I stuck with my original case analysis. Key to making this work was the "case analysis" and "proof by contradiction" custom blocks. Also @lohner 's work on how to prove ∃x.P(x)→⏊

Thanks!

**Comment by michaelgwelch** [comment]
I revisit these problems every few months and often have to refer to my notes to be able to solve the 2 or 3 problems like this one.

And I see that recent version of the The Incredible Proof Machine now include a "smallest number of blocks" solution. (I'm currently working on proving that `(∀x.P(x)) -> ⏊`  implies `∃x.P(x) -> ⏊`  (which ironically is, I think, one problem I submitted via a PR)

My best solution takes 16 blocks (I think. Not sure because I've reset it to try to get to 12).

You should sell a hint-book. :-)
