### ISSUE TITLE
Issues using Safari

### ISSUE THREAD

**Issue by michaelgwelch** [nomeata/incredible#72]
I'm using Safari 9 on OS X 10.11.2

I've noticed issues using Safari but til now I could work around.
1. When starting a proof the "proof window" is empty. Dragging any proof rule onto the surface of the proof window forces a redraw and then the assumptions and consequence become visible. This has been my work around.
2. Can't create a custom block. This I couldn't work around. Switched to Firefox to accomplish. Basically, you can't multi-select. If I shift click on a block the proof window becomes non-responsive. To make it responsive again, I need to drag a new symbol on to the proof. At this point the original block is no longer selected. So no progress can be made in multi-selecting.

I assume the developers don't use Safari so I don't know how much attention this will get. I raise it to your attention in case anyone has a Mac and wants to take a crack at this. My web skills are limited. Not sure I could figure it out.

There are errors in the javascript console on page load. Perhaps these contribute to the problem.

Can't figure out how to copy/paste entire error. I'll summarize
- Can't load messages.json. Cross origin requests are only supported for HTTP 
- Failed to load http://incredible.nomeata.de/vendor/backbone-min.map (404 error)

**Comment by michaelgwelch** [comment]
Please ignore the first javascript error. Now that I look closely it's related to an extension I have loaded from Evernote.

**Comment by nomeata** [comment]
I doubt that the java script errors are related; they would break more. It’s probably just non-portable JavaScript code written be me.

I’m happy to take hints or patches, but I’m unable to work it out myself, due to lack of Safari browser.

**Comment by michaelgwelch** [comment]
Understood. I'll investigate further and see if I can learn more.

**Comment by nomeata** [comment]
Thanks!

**Comment by michaelgwelch** [comment]
Just noticed this old issue. I've been using Safari lately without issue, so I'll close this.

**Comment by nomeata** [comment]
Thanks!
