### ISSUE TITLE
Red arrows can be hidden behind text.

### ISSUE THREAD

**Issue by roSievers** [nomeata/incredible#78]
When I was writing a lemma, I changed something around which broke the proof. But no error was visible, because the long text hid the complete arrow behind.

I believe it would be helpful to ensure errors are always clearly visible and can't be obscured. (e.g. make the text color dark red.)

**Comment by nomeata** [comment]
This is certainly true, but quite a general remark, and not something that is easily actionable. I know that the interface is not perfect. Do you have a more concrete suggestion?

**Comment by roSievers** [comment]
No I don't have one yet. It was just something that took me a while to figure out, so I decided to post about it.

**Comment by nomeata** [comment]
Ok. Then please do not be insulted if I move this off the list of open issue. It is still useful input, but i want to keep this list short and useful, e.g. lists of concrete things to do (or at least very concrete bugs). You are very welcome to re-open the bug once things get more concrete here.
