### ISSUE TITLE
Menu hides initial logic blocks

### ISSUE THREAD

**Issue by UniQP** [nomeata/incredible#79]
For smaller screen widths the menu bar hides the initial logic blocks (see attachment). I guess it's a good idea to center all initial blocks vertically.

![pm](https://cloud.githubusercontent.com/assets/1321557/12260089/f9dce1f6-b919-11e5-9b7c-4e67989ee643.png)

**Comment by nomeata** [comment]
Ah, right. Thanks for the reminder. I’ll take care of it right away, lest I forget again and again :-)
