### ISSUE TITLE
Minimal number of blocks

### ISSUE THREAD

**Issue by nomeata** [nomeata/incredible#82]
It would be nice if the session specification allowed for a field to indicate the minimal number of block needed, and then have the UI tell the user about how well he is doing

Also suggested by an ITP reviewer:

> For each proof, there is a minimal number of blocks and
> connections that are needed to complete it. Many games tell you
> how close you are to optimal, so that you can try to find the
> "best" proof. Finding the "best" proof is often
> educational. Consider making this part of the game.

**Comment by nomeata** [comment]
Working on that right now. UI is tricky, and I need to take custom blocks into account.

**Comment by NightRa** [comment]
Also the naming helper block shouldn't be counted.

**Comment by nomeata** [comment]
True!
