### ISSUE TITLE
Improve build system

### ISSUE THREAD

**Issue by larsrh** [nomeata/incredible#90]
The instructions in the README are outdated, and following along the Travis scripts only works on Debian derivatives. The `Makefile` doesn't quite work if you want to use sandboxes.

I would suggest offering a Stack-based build to make it more reproducible. If I have some spare time I can try to work on this.

**Comment by nomeata** [comment]
>  If I have some spare time I can try to work on this.

I like that :-)

**Comment by larsrh** [comment]
I managed to get the GHCJS parts building with Stack. But it turns out that many vital components are missing, because `install-jslibs.sh` tries to download non-existing URLs. I think it would probably make sense to track the `vendor` directory in Git.

**Comment by nomeata** [comment]
Hmm. I guess that is how one does package management these days then…

**Comment by larsrh** [comment]
I have [asked around](https://twitter.com/larsr_h/status/791553538602180608) on Twitter, and there seems to be a better solution. I will add this to my list of things to investigate :smile:
