### ISSUE TITLE
Custom blocks?

### ISSUE THREAD

**Issue by benzrf** [nomeata/incredible#93]
There doesn't seem to be any way of creating custom blocks anymore. That, or it's non-obvious enough that it'd be nice to have an explanation somewhere on the page. If the feature is supposed to be removed entirely, it'd be nice to get rid of the "custom blocks" heading on the left to prevent the illusion of its existence!

**Comment by nomeata** [comment]
I know that the Incredible Proof Machine lacks a manual – but you can still create custom blocks. Just Shift-Click one or more blocks in your proof, and it will offer you to create a custom block from it. (If it can – with too-complicated proof fragments that might not be possible.)
