### ISSUE TITLE
~(A OR ~~A) without LEM?

### ISSUE THREAD

**Issue by TimJSwan89** [nomeata/incredible#99]
I apologize for creating an issue, but I tried emailing about this and didn't see a response after seeing activity on here.

I am stuck on the last challenge for session 4: Prove ~(A OR ~~A) without LEM block yet available.

**Comment by nomeata** [comment]
Sorry for the slow response by mail, not much at the computer over christmas…

Yeah the last one is a tricky one (thanks to @lohner), but it is solvable… Not sure how to help here, though: I don't want to spoil the fun. But rest assured: It is possible!
